<a href="https://colab.research.google.com/github/Sourabh03github/Python/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [12]:
# pd.DataFrame is a function that takes 1) Data 2) Index for rows 3) for columns

df = pd.DataFrame(np.arange(0,30).reshape(5,6), index=['Row1','Row2','Row3','Row4','Row5'], columns=['Column1','Column2','Column3','Column4','Column5','Column6'])

In [13]:
df.head()

      Column1  Column2  Column3  Column4  Column5  Column6
Row1        0        1        2        3        4        5
Row2        6        7        8        9       10       11
Row3       12       13       14       15       16       17
Row4       18       19       20       21       22       23
Row5       24       25       26       27       28       29

In [14]:
df.loc['Row1']

# this function focuses on rows and shows all the data related to the given row

Column1    0
Column2    1
Column3    2
Column4    3
Column5    4
Column6    5
Name: Row1, dtype: int64

In [15]:
# iloc[ ] function - In this as we used to give rows and column for accessing the 2D array elements in similar way we have to give here.

df.iloc[:,:]

# this will show all the rows and columns and if we want particular part form this we can aslo do that by mentions till what row or col we want.

      Column1  Column2  Column3  Column4  Column5  Column6
Row1        0        1        2        3        4        5
Row2        6        7        8        9       10       11
Row3       12       13       14       15       16       17
Row4       18       19       20       21       22       23
Row5       24       25       26       27       28       29

In [16]:
# We can also convert our DataFrame into arrays

df.iloc[:,:].values

# By using iloc function we can convert it into Arrays.

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [17]:
# To check our DataFrame contains Null values We can make use of the isNull funvtion and Sum function with our DATAFRAME

df.isnull().sum()

# now out Data does not contain any Null values so it should show 0

Column1    0
Column2    0
Column3    0
Column4    0
Column5    0
Column6    0
dtype: int64

In [18]:
# Undrstanding Pandas Read Operations

In [19]:
# Using this pd.read_csv() function we can read any csv file that we have uploaded and this will by default show first 5 data

df = pd.read_csv('sample_test_data.csv')

In [20]:
# df.head() this function is used to display what content CSV file has.

df.head()

   ID     Name  Age       City Department  Salary
0   1    Alice   24       Pune         IT   55000
1   2      Bob   31     Mumbai         HR   62000
2   3  Charlie   28      Delhi    Finance   70000
3   4    David   35  Bengaluru      Sales   48000
4   5     Emma   22  Hyderabad  Marketing   51000

In [21]:
# df.info() function - This gives more information about the CSV file

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   City        10 non-null     object
 4   Department  10 non-null     object
 5   Salary      10 non-null     int64
dtypes: int64(3), object(3)
memory usage: 612.0+ bytes

In [22]:
# df.describe() -  This will show some extra information about the file.

df.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  29.500000  61000.000000
std     3.02765   5.400617  11595.018087
min     1.00000  22.000000  46000.000000
25%     3.25000  26.250000  52000.000000
50%     5.50000  28.500000  60500.000000
75%     7.75000  32.500000  68500.000000
max    10.00000  40.000000  82000.000000

In [23]:
# String IO function

from io import StringIO, BytesIO

In [24]:
data = ('col1,col2,col3\n'
        'x, y, 1\n'
        'a, b, 2\n'
        'c, d, 3')

In [25]:

# Using StringIO function you are actually reading raw/hard coded data and creating it into DataFrame.

pd.read_csv(StringIO(data))

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [26]:
# Also if we want particular columns then we can do that as well

df = pd.read_csv(StringIO(data), usecols=['col1','col3'], skipinitialspace=True)

In [27]:
df.head()

  col1  col3
0    x     1
1    a     2
2    c     3

In [28]:
# To access the particular element from the data


df['col1']

0    x
1    a
2    c
Name: col1, dtype: object

In [30]:
df['col1'][2]

'c'

In [3]:
# here we are taking or creating a json data(hard coded) and the with the help of pd.read_json which is a function used to read json data. Using that function we are reading the json data.


Data = '{"Name" : "Sourabh", "email":"Sourabh@gmail.com", "job_profile":[{"title1":"Team Lead"}]}'
pd.read_json(Data)

/tmp/ipykernel_728/2556625355.py:5: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(Data)

      Name              email              job_profile
0  Sourabh  Sourabh@gmail.com  {'title1': 'Team Lead'}

In [4]:
# we can also convert our json file into csv file using to_csv function
# we can also read html file need to use different function
# also we can read excel files and many more.

In [5]:
# Pickling
# It is used to save data structure to disk using pickle format
# any data structure that we create or any excel file/ csv file/ html file is converted into pickle and then we can just load that pickle file.

In [8]:
# here we are reading a Excel File that we have created using read_excel function
df_excel = pd.read_excel('Renovation Estimate - Copy_Test.xlsx')
df_excel.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,Renovation Cost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Task(Major),NaN,NaN,Cost,NaN,NaN,Status,NaN,NaN,NaN,NaN,NaN,Task(To do month by month)
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_excel.to_pickle('df_excel')


# inside our directory this file will get saved in pickle format (df_excel - this will be the name of the file)

In [11]:
df = pd.read_pickle('df_excel')
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,Renovation Cost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Task(Major),NaN,NaN,Cost,NaN,NaN,Status,NaN,NaN,NaN,NaN,NaN,Task(To do month by month)
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN